# Generated by Django 3.1.12 on 2025-01-12 16:33

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagementApp.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
            bases=('inventoryManagementApp.basemodel',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagementApp.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[utils.validators.custom_email_validator])),
                ('phone', models.CharField(max_length=10, validators=[utils.validators.phone_number_validator])),
                ('address', models.TextField()),
            ],
            bases=('inventoryManagementApp.basemodel',),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagementApp.basemodel')),
                ('quantity', models.IntegerField(default=0)),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3)),
                ('movement_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('product_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryManagementApp.product')),
            ],
            bases=('inventoryManagementApp.basemodel',),
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagementApp.basemodel')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('sale_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('product_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryManagementApp.product')),
            ],
            bases=('inventoryManagementApp.basemodel',),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryManagementApp.supplier'),
        ),
    ]
