# Generated by Django 3.1.12 on 2025-01-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product', to='inventoryManagementApp.supplier'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='product_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_saleorder', to='inventoryManagementApp.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='inventoryManagementApp.product'),
        ),
    ]
